/* JS */ gapi.loaded_0(function(_){var window=this;
var ba,ca,da,ha,ia,Fa,Ga;
for(_.g,_.n=function(a){return function(){return ba[a].apply(this,arguments)}},_.r=function(a,b){return ba[a]=b},_._DumpException=function(a){throw a;},ba=[],ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},da="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this,
ha=["String","prototype","startsWith"],ia=0;ia<ha.length-1;ia++){var ka=ha[ia];ka in da||(da[ka]={});da=da[ka]}
var la=ha[ha.length-1],pa=da[la],qa=pa?pa:function(a,b){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");c=this+"";a+="";var d=c.length,e=a.length;b=Math.max(0,Math.min(b|0,c.length));for(var f=0;f<e&&b<d;)if(c[b++]!=a[f++])return!1;return f>=e};qa!=pa&&null!=qa&&ca(da,la,{configurable:!0,writable:!0,value:qa});
_.xa=_.xa||{};_.t=this;_.za=function(a){return void 0!==a};
_.Aa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.Ba=function(a){return"array"==_.Aa(a)};_.Ca=function(a){var b=_.Aa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.u=function(a){return"string"==typeof a};_.Da="closure_uid_"+(1E9*Math.random()>>>0);Fa=function(a,b,c){return a.call.apply(a.bind,arguments)};
Ga=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.z=function(a,b,c){_.z=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?Fa:Ga;return _.z.apply(null,arguments)};_.Ia=Date.now||function(){return+new Date};
_.A=function(a,b){function c(){}c.prototype=b.prototype;a.R=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Is=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.La=window.osapi=window.osapi||{};_.google=window.google||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{rms:"migrated"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},udc_webconsentflow:{url:"https://myaccount.google.com/webconsent?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},
requestCache:{enabled:!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:!0},transport:{isProxyShared:!0},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});

/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
_.D=function(a,b){a=a.split(".");var c=_.t;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.za(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}};_.Oa=window;_.Pa=window.document;_.Qa=_.Oa.location;_.Ra=/\[native code\]/;_.Sa=function(a,b,c){return a[b]=a[b]||c};_.Ta=function(){var a;if((a=Object.create)&&_.Ra.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.Ua=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)}; _.Va=function(a,b){a=a||{};for(var c in a)_.Ua(a,c)&&(b[c]=a[c])};_.Wa=_.Sa(_.Oa,"gapi",{});
_.Xa=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.Ya=new RegExp(/^/.source+/([a-zA-Z][-+.a-zA-Z0-9]*:)?/.source+/(\/\/[^\/?#]*)?/.source+/([^?#]*)?/.source+/(\?([^#]*))?/.source+/(#((#|[^#])*))?/.source+/$/.source);
_.Za=new RegExp(/(%([^0-9a-fA-F%]|[0-9a-fA-F]([^0-9a-fA-F%])?)?)*/.source+/%($|[^0-9a-fA-F]|[0-9a-fA-F]($|[^0-9a-fA-F]))/.source,"g");_.ab=function(){return _.Oa.location.origin||_.Oa.location.protocol+"//"+_.Oa.location.host};_.bb=new RegExp(/\/?\??#?/.source+"("+/[\/?#]/i.source+"|"+/[\uD800-\uDBFF]/i.source+"|"+/%[c-f][0-9a-f](%[89ab][0-9a-f]){0,2}(%[89ab]?)?/i.source+"|"+/%[0-9a-f]?/i.source+")$","i");
_.fb=function(a,b,c){_.eb(a,b,c,"add","at")};_.eb=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.gb=_.Sa(_.Oa,"___jsl",_.Ta());_.Sa(_.gb,"I",0);_.Sa(_.gb,"hel",10);var hb,kb,lb,nb,pb,qb;hb=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};kb=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};lb=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};nb=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]&&b[c]&&"object"===typeof a[c]&&"object"===typeof b[c]&&!lb(a[c])&&!lb(b[c])?nb(a[c],b[c]):b[c]&&"object"===typeof b[c]?(a[c]=lb(b[c])?[]:{},nb(a[c],b[c])):a[c]=b[c])};
pb=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var b;try{b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
qb=function(a){kb(!0);var b=window.___gcfg,c=hb("cu");if(b&&b!==window.___gu){var d={};nb(d,b);c.push(d);window.___gu=b}var b=hb("cu"),e=window.document.scripts||window.document.getElementsByTagName("script")||[],d=[],f=[];f.push.apply(f,hb("us"));for(var h=0;h<e.length;++h)for(var k=e[h],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",
!0),(f=d[e])?(h=f.nodeType,f=3==h||4==h?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=pb(f))&&b.push(f));a&&(d={},nb(d,a),c.push(d));d=hb("cd");a=0;for(b=d.length;a<b;++a)nb(kb(),d[a]);d=hb("ci");a=0;for(b=d.length;a<b;++a)nb(kb(),d[a]);a=0;for(b=c.length;a<b;++a)nb(kb(),c[a])};_.E=function(a,b){if(!a)return kb();a=a.split("/");for(var c=kb(),d=0,e=a.length;c&&"object"===typeof c&&d<e;++d)c=c[a[d]];return d===a.length&&void 0!==c?c:b}; _.rb=function(a,b){var c=a;if("string"===typeof a){var d=c={};a=a.split("/");for(var e=0,f=a.length;e<f-1;++e)var h={},d=d[a[e]]=h;d[a[e]]=b}qb(c)};
var tb=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.Sa(_.gb,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};tb&&tb();qb();_.D("gapi.config.get",_.E);_.D("gapi.config.update",_.rb);
_.Bj=window.googleapis&&window.googleapis.server||{};
_.Kj=function(){var a=/\s*;\s*/;return{get:function(b,c){b+="=";for(var d=(window.document.cookie||"").split(a),e=0,f;f=d[e];++e)if(0==f.indexOf(b))return f.substr(b.length);return c}}}();
var Mj,Nj;
_.Lj={KJ:"Authorization",wB:"Content-ID",JU:"Content-Transfer-Encoding",Ug:"Content-Type",MU:"Date",fW:"OriginToken",LX:"WWW-Authenticate",YK:"X-ClientDetails",OX:"X-Goog-AuthUser",ZK:"X-Goog-Encode-Response-If-Executable",$K:"X-Goog-Meeting-Botguardid",aL:"X-Goog-Meeting-Debugid",bL:"X-Goog-Meeting-Token",PX:"X-Goog-PageId",$B:"X-Goog-Safety-Content-Type",aC:"X-Goog-Safety-Encoding",cL:"X-HTTP-Method-Override",bC:"X-JavaScript-User-Agent",dL:"X-Origin",cC:"X-Referer",eL:"X-Requested-With",QX:"X-Use-HTTP-Status-Code-Override"};
Mj=["Accept","Accept-Language",_.Lj.KJ,"Cache-Control","Content-Disposition","Content-Encoding","Content-Language","Content-Length","Content-MD5","Content-Range",_.Lj.Ug,_.Lj.MU,"GData-Version","Host","If-Match","If-Modified-Since","If-None-Match","If-Unmodified-Since","Origin",_.Lj.fW,"Pragma","Range","Slug","Transfer-Encoding","Want-Digest",_.Lj.YK,"X-GData-Client","X-GData-Key",_.Lj.OX,_.Lj.PX,_.Lj.ZK,"X-Goog-Correlation-Id","X-Goog-Request-Info","X-Goog-Experiments","x-goog-iam-authority-selector",
"x-goog-iam-authorization-token","X-Goog-Spatula","X-Goog-Upload-Command","X-Goog-Upload-Content-Disposition","X-Goog-Upload-Content-Length","X-Goog-Upload-Content-Type","X-Goog-Upload-File-Name","X-Goog-Upload-Offset","X-Goog-Upload-Protocol","X-Goog-Visitor-Id",_.Lj.cL,_.Lj.bC,"X-Pan-Versionid","X-Proxied-User-IP",_.Lj.dL,_.Lj.cC,_.Lj.eL,"X-Upload-Content-Length","X-Upload-Content-Type",_.Lj.QX,"X-Ios-Bundle-Identifier","X-Android-Package","X-Ariane-Xsrf-Token","X-YouTube-VVT","X-YouTube-Page-CL",
"X-YouTube-Page-Timestamp",_.Lj.$K,_.Lj.aL,_.Lj.bL];
Nj=["Digest","Cache-Control","Content-Disposition","Content-Encoding","Content-Language","Content-Length","Content-MD5","Content-Range",_.Lj.Ug,"Date","ETag","Expires","Last-Modified","Location","Pragma","Range","Server","Transfer-Encoding",_.Lj.LX,"Vary","Unzipped-Content-MD5","X-Goog-Generation","X-Goog-Metageneration",_.Lj.$B,_.Lj.aC,"X-Google-Trace","X-Goog-Upload-Chunk-Granularity","X-Goog-Upload-Control-URL","X-Goog-Upload-Size-Received","X-Goog-Upload-Status","X-Goog-Upload-URL","X-Goog-Diff-Download-Range", "X-Goog-Hash","X-Goog-Updated-Authorization","X-Server-Object-Version","X-Guploader-Customer","X-Guploader-Upload-Result","X-Guploader-Uploadid","X-Google-Gfe-Backend-Request-Cost",_.Lj.$K,_.Lj.aL,_.Lj.bL];
var Oj,Pj,Qj,Rj,Tj,Uj,Vj,Wj,Xj,Yj,Zj,ak;Oj=null;Pj=null;Qj=null;Rj=function(a,b){var c=a.length;if(c!=b.length)return!1;for(var d=0;d<c;++d){var e=a.charCodeAt(d),f=b.charCodeAt(d);65<=e&&90>=e&&(e+=32);65<=f&&90>=f&&(f+=32);if(e!=f)return!1}return!0};
_.Sj=function(a){a=String(a||"").split("\x00").join("");for(var b=[],c=!0,d=0,e=a.length;d<e;++d){var f=a.charAt(d),h=a.charCodeAt(d);if(55296<=h&&56319>=h&&d+1<e){var k=a.charAt(d+1),l=a.charCodeAt(d+1);56320<=l&&57343>=l&&(f+=k,h=65536+(h-55296<<10)+(l-56320),++d)}if(!(0<=h&&1114109>=h)||55296<=h&&57343>=h||64976<=h&&65007>=h||65534==(h&65534))h=65533,f=String.fromCharCode(h);k=!(32<=h&&126>=h)||" "==f||c&&":"==f||"\\"==f;!c||"/"!=f&&"?"!=f||(c=!1);"%"==f&&(d+2>=e?k=!0:(l=16*(0,window.parseInt)(a.charAt(d+
1),16)+(0,window.parseInt)(a.charAt(d+2),16),0<=l&&255>=l?(h=l,f=0==h?"":"%"+(256+l).toString(16).toUpperCase().substr(1),d+=2):k=!0));k&&(f=(0,window.encodeURIComponent)(f),1>=f.length&&(0<=h&&127>=h?f="%"+(256+h).toString(16).toUpperCase().substr(1):(h=65533,f=(0,window.encodeURIComponent)(String.fromCharCode(h)))));b.push(f)}a=b.join("");a=a.split("#")[0];a=a.split("?");b=a[0].split("/");c=[];d=0;for(e=b.length;d<e;++d)f=b[d],h=f.split("%2E").join("."),h=h.split((0,window.encodeURIComponent)("\uff0e")).join("."),
"."==h?d+1==e&&c.push(""):".."==h?(0<c.length&&c.pop(),d+1==e&&c.push("")):c.push(f);a[0]=c.join("/");for(a=a.join("?");a&&"/"==a.charAt(0);)a=a.substr(1);return"/"+a};Tj={"access-control-allow-origin":!0,"access-control-allow-credentials":!0,"access-control-expose-headers":!0,"access-control-max-age":!0,"access-control-allow-headers":!0,"access-control-allow-methods":!0,p3p:!0,"proxy-authenticate":!0,"set-cookie":!0,"set-cookie2":!0,status:!0,tsv:!0,"":!0};
Uj={"access-control-request-headers":!0,"access-control-request-method":!0,"client-ip":!0,clientip:!0,connection:!0,cookie:!0,cookie2:!0,date:!0,dnt:!0,forwarded:!0,"forwarded-for":!0,"front-end-https":!0,host:!0,"max-forwards":!0,method:!0,origin:!0,"proxy-authorization":!0,"proxy-connection":!0,"raw-post-data":!0,referer:!0,upgrade:!0,url:!0,"user-agent":!0,version:!0,via:!0,"x-att-deviceid":!0,"x-client-ip":!0,"x-do-not-track":!0,"x-forwarded-by":!0,"x-forwarded-for":!0,"x-forwarded-host":!0,"x-forwarded-proto":!0,
"x-geo":!0,"x-origin":!0,"x-proxyuser-ip":!0,"x-real-ip":!0,"x-referer":!0,"x-uidh":!0,"x-user-ip":!0,"x-wap-profile":!0,"":!0};Vj=function(a){if(!_.Ca(a))return null;for(var b={},c=0;c<a.length;c++){var d=a[c];if("string"===typeof d&&d){var e=d.toLowerCase();Rj(d,e)&&(b[e]=d)}}for(var f in _.Lj)Object.prototype.hasOwnProperty.call(_.Lj,f)&&(d=_.Lj[f],e=d.toLowerCase(),Rj(d,e)&&Object.prototype.hasOwnProperty.call(b,e)&&(b[e]=d));return b};
Wj=new RegExp("("+/[\t -~\u00A0-\u2027\u202A-\uD7FF\uE000-\uFFFF]/.source+"|"+/[\uD800-\uDBFF][\uDC00-\uDFFF]/.source+"){1,100}","g");Xj=/[ \t]*(\r?\n[ \t]+)+/g;Yj=/^[ \t]+|[ \t]+$/g;Zj=function(a,b){if(!b&&"object"===typeof a&&a&&"number"===typeof a.length){b=a;a="";for(var c=0,d=b.length;c<d;++c){var e=Zj(b[c],!0);e&&(a&&(e=a+", "+e),a=e)}}if("string"===typeof a&&(a=a.replace(Xj," "),a=a.replace(Yj,""),""==a.replace(Wj,"")&&a))return a};ak=/^[-0-9A-Za-z!#\$%\&'\*\+\.\^_`\|~]+$/g;
_.bk=function(a){if("string"!==typeof a||!a||!a.match(ak))return null;a=a.toLowerCase();if(null==Qj){var b=[],c=_.E("googleapis/headers/response");c&&"object"===typeof c&&"number"===typeof c.length||(c=null);null!=c&&(b=b.concat(c));(c=_.E("client/headers/response"))&&"object"===typeof c&&"number"===typeof c.length||(c=null);null!=c&&(b=b.concat(c));b=b.concat(Nj);(c=_.E("googleapis/headers/request"))&&"object"===typeof c&&"number"===typeof c.length||(c=null);null!=c&&(b=b.concat(c));(c=_.E("client/headers/request"))&&
"object"===typeof c&&"number"===typeof c.length||(c=null);null!=c&&(b=b.concat(c));var b=b.concat(Mj),d;for(d in _.Lj)Object.prototype.hasOwnProperty.call(_.Lj,d)&&b.push(_.Lj[d]);Qj=Vj(b)}return null!=Qj&&Qj.hasOwnProperty(a)?Qj[a]:a};
_.ck=function(a,b){if(!_.bk(a)||!Zj(b))return null;a=a.toLowerCase();if(a.match(/^x-google|^x-gfe/i)||Uj[a])return null;if(null==Oj){b=[];var c=_.E("googleapis/headers/request");c&&"object"===typeof c&&"number"===typeof c.length||(c=null);null!=c&&(b=b.concat(c));(c=_.E("client/headers/request"))&&"object"===typeof c&&"number"===typeof c.length||(c=null);null!=c&&(b=b.concat(c));b=b.concat(Mj);Oj=Vj(b)}return null!=Oj&&Oj.hasOwnProperty(a)?Oj[a]:null};
_.dk=function(a,b){if(!_.bk(a)||!Zj(b))return null;a=a.toLowerCase();if(Tj[a])return null;if(null==Pj){b=[];var c=_.E("googleapis/headers/response");c&&"object"===typeof c&&"number"===typeof c.length||(c=null);null!=c&&(b=b.concat(c));(c=_.E("client/headers/response"))&&"object"===typeof c&&"number"===typeof c.length||(c=null);null!=c&&(b=b.concat(c));b=b.concat(Nj);Pj=Vj(b)}return null!=Pj&&Pj.hasOwnProperty(a)?a:null};
_.ek=function(a,b){if(_.bk(b)&&null!=a&&"object"===typeof a){var c=void 0,d;for(d in a)if(Object.prototype.hasOwnProperty.call(a,d)&&Rj(d,b)){var e=Zj(a[d]);e&&(void 0!==c&&(e=c+", "+e),c=e)}return c}};_.fk=function(a,b,c,d){var e=_.bk(b);if(e){c&&(c=Zj(c));b=b.toLowerCase();for(var f in a)Object.prototype.hasOwnProperty.call(a,f)&&Rj(f,b)&&delete a[f];c&&(d||(b=e),a[b]=c)}};
_.gk=function(a,b){var c={};if(!a)return c;a=a.split("\r\n");for(var d=0,e=a.length;d<e;++d){var f=a[d];if(!f)break;var h=f.indexOf(":");if(!(0>=h)){var k=f.substring(0,h);if(k=_.bk(k)){for(f=f.substring(h+1);d+1<e&&a[d+1].match(/^[ \t]/);)f+="\r\n"+a[d+1],++d;if(f=Zj(f))if(k=_.dk(k,f)||(b?void 0:k))k=k.toLowerCase(),h=_.ek(c,k),void 0!==h&&(f=h+", "+f),_.fk(c,k,f,!0)}}}return c};

(function(){function a(a,b){if(!(a<c)&&d)if(2===a&&d.warn)d.warn(b);else if(3===a&&d.error)try{d.error(b)}catch(h){}else d.log&&d.log(b)}var b=function(b){a(1,b)};_.Ja=function(b){a(2,b)};_.Ka=function(b){a(3,b)};_.wb=function(){};b.INFO=1;b.WARNING=2;b.NONE=4;var c=1,d=window.console?window.console:window.opera?window.opera.postError:void 0;return b})();

_.F=_.F||{};
_.F=_.F||{};(function(){var a=[];_.F.Wja=function(b){a.push(b)};_.F.jka=function(){for(var b=0,c=a.length;b<c;++b)a[b]()}})();
_.xb=function(a){return!!a&&"object"===typeof a&&_.Ra.test(a.push)};_.yb=function(a,b){var c=_.Sa(_.gb,"watt",_.Ta());_.Sa(c,a,b)};_.F=_.F||{};
(function(){var a=null;_.F.Wc=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");for(var e=window.decodeURIComponent?window.decodeURIComponent:window.unescape,f=0,h=b.length;f<h;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k),k=b[f].substring(k+1),k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(m){}}}c&&(a=d);return d}; _.F.Wc()})();
_.D("gadgets.util.getUrlParameters",_.F.Wc);
_.Ab=window.console;_.Bb=function(a){_.Ab&&_.Ab.log&&_.Ab.log(a)};_.Cb=function(){};
_.Db=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&_.rb(a());return{register:function(a,c,d){d&&d(_.E())},get:function(a){return _.E(a)},update:function(a,c){if(c)throw"Config replacement is not supported";_.rb(a)},xc:function(){}}}();
_.D("gadgets.config.register",_.Db.register);_.D("gadgets.config.get",_.Db.get);_.D("gadgets.config.init",_.Db.xc);_.D("gadgets.config.update",_.Db.update);
var Eb=function(a){return 10>a?"0"+a:a},Fb={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},Hb=function(a){var b,c,d;b=/[\"\\\x00-\x1f\x7f-\x9f]/g;if(void 0!==a){switch(typeof a){case "string":return b.test(a)?'"'+a.replace(b,function(a){var b=Fb[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";
b=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){d=a.length;for(c=0;c<d;c+=1)b.push(Hb(a[c])||"null");return"["+b.join(",")+"]"}for(c in a)!/___$/.test(c)&&_.Ua(a,c)&&"string"===typeof c&&(d=Hb(a[c]))&&b.push(Hb(c)+":"+d);return"{"+b.join(",")+"}"}return""}},Ib=function(a){if(!a)return!1;if(/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))try{return eval("("+
a+")")}catch(b){}return!1},Jb=!1,Kb;try{Jb=!!window.JSON&&'["a"]'===window.JSON.stringify(["a"])&&"a"===window.JSON.parse('["a"]')[0]}catch(a){}Kb=function(a){try{return window.JSON.parse(a)}catch(b){return!1}};_.Mb=Jb?window.JSON.stringify:Hb;_.Nb=Jb?Kb:Ib;Kb||(Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",Eb(this.getUTCMonth()+1),"-",Eb(this.getUTCDate()),"T",Eb(this.getUTCHours()),":",Eb(this.getUTCMinutes()),":",Eb(this.getUTCSeconds()),"Z"].join("")});

_.D("gadgets.json.stringify",_.Mb);_.D("gadgets.json.parse",_.Nb);_.Xa(_.Oa.location.href,"rpctoken")&&_.fb(_.Pa,"unload",function(){});
var Qb;_.Ob=function(){var a=_.Pa.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.Pb=function(a){if(_.Ob())a();else{var b=!1,c=function(){if(!b)return b=!0,a.apply(this,arguments)};_.Oa.addEventListener?(_.Oa.addEventListener("load",c,!1),_.Oa.addEventListener("DOMContentLoaded",c,!1)):_.Oa.attachEvent&&(_.Oa.attachEvent("onreadystatechange",function(){_.Ob()&&c.apply(this,arguments)}),_.Oa.attachEvent("onload",c))}};Qb=Qb||{};Qb.VR=null; Qb.oQ=null;Qb.Vy=null;Qb.frameElement=null;
Qb=Qb||{};
Qb.CJ||(Qb.CJ=function(){function a(a){"undefined"!=typeof window.addEventListener?window.addEventListener("message",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onmessage",a);window.___jsl=window.___jsl||{};var b=window.___jsl;b.RPMQ=b.RPMQ||[];b.RPMQ.push(a)}function b(a){var b=(0,_.Nb)(a.data);if(b&&b.f){(0,_.wb)("gadgets.rpc.receive("+window.name+"): "+a.data);var d=_.G.Hn(b.f);e&&("undefined"!==typeof a.origin?a.origin!==d:a.domain!==/^.+:\/\/([^:]+).*/.exec(d)[1])?_.Ka("Invalid rpc message origin. "+
d+" vs "+(a.origin||"")):c(b,a.origin)}}var c,d,e=!0;return{Jp:function(){return"wpm"},l4:function(){return!0},xc:function(f,h){_.Db.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(e=!1)});c=f;d=h;a(b);d("..",!0);return!0},xd:function(a){d(a,!0);return!0},call:function(a,b,c){var d=_.G.Hn(a),e=_.G.fL(a);d?window.setTimeout(function(){var a=(0,_.Mb)(c);(0,_.wb)("gadgets.rpc.send("+window.name+"): "+a);e.postMessage(a,d)},0):".."!=a&&_.Ka("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.G&&_.G||(_.G=window.gadgets.rpc,_.G.config=_.G.config,_.G.register=_.G.register,_.G.unregister=_.G.unregister,_.G.yR=_.G.registerDefault,_.G.TT=_.G.unregisterDefault,_.G.kN=_.G.forceParentVerifiable,_.G.call=_.G.call,_.G.$t=_.G.getRelayUrl,_.G.uj=_.G.setRelayUrl,_.G.EA=_.G.setAuthToken,_.G.Qv=_.G.setupReceiver,_.G.xn=_.G.getAuthToken,_.G.tH=_.G.removeReceiver,_.G.SN=_.G.getRelayChannel,_.G.uR=_.G.receive,_.G.vR=_.G.receiveSameDomain,_.G.mb=
_.G.getOrigin,_.G.Hn=_.G.getTargetOrigin,_.G.fL=_.G._getTargetWin,_.G.UX=_.G._parseSiblingId);else{_.G=function(){function a(a,b){if(!ja[a]){var c=M;b||(c=ua);ja[a]=c;b=sa[a]||[];for(var d=0;d<b.length;++d){var e=b[d];e.t=N[a];c.call(a,e.f,e)}sa[a]=[]}}function b(){function a(){sb=!0}V||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),V=!0)}function c(a,c,d,e,f){N[c]&&N[c]===d||(_.Ka("Invalid gadgets.rpc token. "+
N[c]+" vs "+d),na(c,2));f.onunload=function(){L[c]&&!sb&&(na(c,1),_.G.tH(c))};b();e=(0,_.Nb)((0,window.decodeURIComponent)(e))}function d(b,c){if(b&&"string"===typeof b.s&&"string"===typeof b.f&&b.a instanceof Array)if(N[b.f]&&N[b.f]!==b.t&&(_.Ka("Invalid gadgets.rpc token. "+N[b.f]+" vs "+b.t),na(b.f,2)),"__ack"===b.s)window.setTimeout(function(){a(b.f,!0)},0);else{b.c&&(b.callback=function(a){_.G.call(b.f,(b.g?"legacy__":"")+"__cb",null,b.c,a)});if(c){var d=e(c);b.origin=c;var f=b.r,h;try{h=e(f)}catch(oa){}f&&
h==d||(f=c);b.referer=f}c=(y[b.s]||y[""]).apply(b,b.a);b.c&&"undefined"!==typeof c&&_.G.call(b.f,"__cb",null,b.c,c)}}function e(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a)throw Error("b");
var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c}function f(a){if("/"==a.charAt(0)){var b=a.indexOf("|");return{id:0<b?a.substring(1,b):a.substring(1),origin:0<b?a.substring(b+1):null}}return null}function h(a){if("undefined"===typeof a||".."===a)return window.parent;var b=f(a);if(b)return window.top.frames[b.id];a=String(a);return(b=window.frames[a])?b:(b=window.document.getElementById(a))&&b.contentWindow?
b.contentWindow:null}function k(a,b){if(!0!==L[a]){"undefined"===typeof L[a]&&(L[a]=0);var c=h(a);".."!==a&&null==c||!0!==M.xd(a,b)?!0!==L[a]&&10>L[a]++?window.setTimeout(function(){k(a,b)},500):(ja[a]=ua,L[a]=!0):L[a]=!0}}function l(a){(a=B[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function m(a,b,c){b&&!/http(s)?:\/\/.+/.test(b)&&(0==b.indexOf("//")?b=window.location.protocol+
b:"/"==b.charAt(0)?b=window.location.protocol+"//"+window.location.host+b:-1==b.indexOf("://")&&(b=window.location.protocol+"//"+b));B[a]=b;"undefined"!==typeof c&&(H[a]=!!c)}function p(a,b){b=b||"";N[a]=String(b);k(a,b)}function q(a){a=(a.passReferrer||"").split(":",2);Na=a[0]||"none";aa=a[1]||"origin"}function w(b){"true"===String(b.useLegacyProtocol)&&(M=Qb.Vy||ua,M.xc(d,a))}function x(a,b){function c(c){c=c&&c.rpc||{};q(c);var d=c.parentRelayUrl||"",d=e(Y.parent||b)+d;m("..",d,"true"===String(c.useLegacyProtocol));
w(c);p("..",a)}!Y.parent&&b?c({}):_.Db.register("rpc",null,c)}function v(a,b,c){if(".."===a)x(c||Y.rpctoken||Y.ifpctok||"",b);else a:{var d=null;if("/"!=a.charAt(0)){if(!_.F)break a;d=window.document.getElementById(a);if(!d)throw Error("c`"+a);}d=d&&d.src;b=b||_.G.mb(d);m(a,b);b=_.F.Wc(d);p(a,c||b.rpctoken)}}var y={},B={},H={},N={},C=0,K={},L={},Y={},ja={},sa={},Na=null,aa=null,fa=window.top!==window.self,va=window.name,na=function(){},ob=window.console,wa=ob&&ob.log&&function(a){ob.log(a)}||function(){},
ua=function(){function a(a){return function(){wa(a+": call ignored")}}return{Jp:function(){return"noop"},l4:function(){return!0},xc:a("init"),xd:a("setup"),call:a("call")}}();_.F&&(Y=_.F.Wc());var sb=!1,V=!1,M=function(){if("rmr"==Y.rpctx)return Qb.VR;var a="function"===typeof window.postMessage?Qb.CJ:"object"===typeof window.postMessage?Qb.CJ:window.ActiveXObject?Qb.oQ?Qb.oQ:Qb.Vy:0<window.navigator.userAgent.indexOf("WebKit")?Qb.VR:"Gecko"===window.navigator.product?Qb.frameElement:Qb.Vy;a||(a=
ua);return a}();y[""]=function(){wa("Unknown RPC service: "+this.s)};y.__cb=function(a,b){var c=K[a];c&&(delete K[a],c.call(this,b))};return{config:function(a){"function"===typeof a.cS&&(na=a.cS)},register:function(a,b){if("__cb"===a||"__ack"===a)throw Error("d");if(""===a)throw Error("e");y[a]=b},unregister:function(a){if("__cb"===a||"__ack"===a)throw Error("f");if(""===a)throw Error("g");delete y[a]},yR:function(a){y[""]=a},TT:function(){delete y[""]},kN:function(){},call:function(a,b,c,d){a=a||
"..";var e="..";".."===a?e=va:"/"==a.charAt(0)&&(e=_.G.mb(window.location.href),e="/"+va+(e?"|"+e:""));++C;c&&(K[C]=c);var h={s:b,f:e,c:c?C:0,a:Array.prototype.slice.call(arguments,3),t:N[a],l:!!H[a]},k;a:if("bidir"===Na||"c2p"===Na&&".."===a||"p2c"===Na&&".."!==a){k=window.location.href;var l="?";if("query"===aa)l="#";else if("hash"===aa)break a;l=k.lastIndexOf(l);l=-1===l?k.length:l;k=k.substring(0,l)}else k=null;k&&(h.r=k);if(".."===a||null!=f(a)||window.document.getElementById(a))(k=ja[a])||null===
f(a)||(k=M),0===b.indexOf("legacy__")&&(k=M,h.s=b.substring(8),h.c=h.c?h.c:C),h.g=!0,h.r=e,k?(H[a]&&(k=Qb.Vy),!1===k.call(a,e,h)&&(ja[a]=ua,M.call(a,e,h))):sa[a]?sa[a].push(h):sa[a]=[h]},$t:l,uj:m,EA:p,Qv:v,xn:function(a){return N[a]},tH:function(a){delete B[a];delete H[a];delete N[a];delete L[a];delete ja[a]},SN:function(){return M.Jp()},uR:function(a,b){4<a.length?M.hia(a,d):c.apply(null,a.concat(b))},vR:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){d(a)},0)},mb:e,
Hn:function(a){var b=null,c=l(a);c?b=c:(c=f(a))?b=c.origin:".."==a?b=Y.parent:(a=window.document.getElementById(a))&&"iframe"===a.tagName.toLowerCase()&&(b=a.src);return e(b)},xc:function(){!1===M.xc(d,a)&&(M=ua);fa?v(".."):_.Db.register("rpc",null,function(a){a=a.rpc||{};q(a);w(a)})},fL:h,UX:f,n$:"__ack",Nfa:va||"..",cga:0,bga:1,aga:2}}();_.G.xc()};
_.G.config({cS:function(a){throw Error("h`"+a);}});_.wb=_.Cb;_.D("gadgets.rpc.config",_.G.config);_.D("gadgets.rpc.register",_.G.register);_.D("gadgets.rpc.unregister",_.G.unregister);_.D("gadgets.rpc.registerDefault",_.G.yR);_.D("gadgets.rpc.unregisterDefault",_.G.TT);_.D("gadgets.rpc.forceParentVerifiable",_.G.kN);_.D("gadgets.rpc.call",_.G.call);_.D("gadgets.rpc.getRelayUrl",_.G.$t);_.D("gadgets.rpc.setRelayUrl",_.G.uj);_.D("gadgets.rpc.setAuthToken",_.G.EA);_.D("gadgets.rpc.setupReceiver",_.G.Qv);_.D("gadgets.rpc.getAuthToken",_.G.xn); _.D("gadgets.rpc.removeReceiver",_.G.tH);_.D("gadgets.rpc.getRelayChannel",_.G.SN);_.D("gadgets.rpc.receive",_.G.uR);_.D("gadgets.rpc.receiveSameDomain",_.G.vR);_.D("gadgets.rpc.getOrigin",_.G.mb);_.D("gadgets.rpc.getTargetOrigin",_.G.Hn);

_.I={};_.Cc={};window.iframer=_.Cc;
_.Dc=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.Ec=function(a){return"number"==typeof a};_.Fc=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.Gc=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.Hc=2147483648*Math.random()|0;
var Jc;_.Ic=function(a,b){return 0==a.lastIndexOf(b,0)};Jc=0;_.Lc=function(a){return null==a?"":String(a)};_.Mc=function(a){return/^[\s\xa0]*$/.test(a)};_.Nc=function(a){return a[_.Da]||(a[_.Da]=++Jc)};_.Oc=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};_.Pc=function(a){return"function"==_.Aa(a)};
_.Qc=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(_.u(a))return _.u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
_.Rc=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(_.u(a))return _.u(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};_.Sc=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Tc=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=_.u(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var l=h[k];b.call(c,l,k,a)&&(e[f++]=l)}return e};_.Uc=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=_.u(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
_.Vc=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Wc=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};_.Xc=function(a,b){return 0<=(0,_.Qc)(a,b)};
_.Zc=function(a,b){b=(0,_.Qc)(a,b);var c;(c=0<=b)&&_.Yc(a,b);return c};_.Yc=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.$c=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.Ca(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}};

_.ad=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.bd=function(a){a.zF=void 0;a.ya=function(){return a.zF?a.zF:a.zF=new a}};_.cd=function(){};_.dd=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};_.ed=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};_.fd=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1};_.gd=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
a:{var id=_.t.navigator;if(id){var jd=id.userAgent;if(jd){_.hd=jd;break a}}_.hd=""}_.kd=function(a){return-1!=_.hd.indexOf(a)};_.ld=function(){return _.kd("Trident")||_.kd("MSIE")};
var nd,od;_.md=function(){return _.kd("Opera")};nd=function(a,b){return a<b?-1:a>b?1:0};od="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
_.pd=function(a,b){var c=0;a=(0,_.Fc)(String(a)).split(".");b=(0,_.Fc)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=nd(0==f[1].length?0:(0,window.parseInt)(f[1],10),0==h[1].length?0:(0,window.parseInt)(h[1],10))||nd(0==f[2].length,0==h[2].length)||nd(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c};
_.qd=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<od.length;f++)c=od[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};_.rd=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};_.sd=function(){return _.kd("iPhone")&&!_.kd("iPod")&&!_.kd("iPad")};_.td=function(){return _.sd()||_.kd("iPad")||_.kd("iPod")};
var vd=function(a){vd[" "](a);return a},yd;vd[" "]=_.cd;_.wd=function(a,b){try{return vd(a[b]),!0}catch(c){}return!1};yd=function(a,b){var c=xd;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Id,Jd,xd,Rd;_.zd=_.md();_.J=_.ld();_.Ad=_.kd("Edge");_.Cd=_.Ad||_.J;_.Dd=_.kd("Gecko")&&!(-1!=_.hd.toLowerCase().indexOf("webkit")&&!_.kd("Edge"))&&!(_.kd("Trident")||_.kd("MSIE"))&&!_.kd("Edge");_.Ed=-1!=_.hd.toLowerCase().indexOf("webkit")&&!_.kd("Edge");_.Fd=_.Ed&&_.kd("Mobile");_.Gd=_.kd("Macintosh");_.Hd=_.kd("Linux")||_.kd("CrOS");Id=function(){var a=_.t.document;return a?a.documentMode:void 0};
a:{var Kd="",Ld=function(){var a=_.hd;if(_.Dd)return/rv\:([^\);]+)(\)|;)/.exec(a);if(_.Ad)return/Edge\/([\d\.]+)/.exec(a);if(_.J)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Ed)return/WebKit\/(\S+)/.exec(a);if(_.zd)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ld&&(Kd=Ld?Ld[1]:"");if(_.J){var Md=Id();if(null!=Md&&Md>(0,window.parseFloat)(Kd)){Jd=String(Md);break a}}Jd=Kd}_.Nd=Jd;xd={};_.Od=function(a){return yd(a,function(){return 0<=_.pd(_.Nd,a)})};_.Qd=function(a){return Number(_.Pd)>=a}; var Sd=_.t.document;Rd=Sd&&_.J?Id()||("CSS1Compat"==Sd.compatMode?(0,window.parseInt)(_.Nd,10):5):void 0;_.Pd=Rd;

_.xh=function(a){return(0,window.encodeURIComponent)(String(a))};_.yh=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;_.zh=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};_.Ah=function(a,b,c){if(_.Ba(b))for(var d=0;d<b.length;d++)_.Ah(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",_.xh(b))}; _.Bh=function(a,b){for(var c in b)_.Ah(c,b[c],a);return a};

_.hk=function(){return(_.kd("Chrome")||_.kd("CriOS"))&&!_.kd("Edge")};_.ik=function(){return _.kd("Safari")&&!(_.hk()||_.kd("Coast")||_.md()||_.kd("Edge")||_.kd("Silk")||_.kd("Android"))};_.jk=function(){return _.kd("Firefox")};_.kk=function(a){for(var b={},c=0,d=0;d<a.length;){var e=a[d++],f;f=e;f=_.Dc(f)?"o"+_.Nc(f):(typeof f).charAt(0)+f;Object.prototype.hasOwnProperty.call(b,f)||(b[f]=!0,a[c++]=e)}a.length=c};_.lk=_.jk();_.mk=_.sd()||_.kd("iPod");_.nk=_.kd("iPad"); _.ok=_.kd("Android")&&!(_.hk()||_.jk()||_.md()||_.kd("Silk"));_.pk=_.hk();_.qk=_.ik()&&!_.td();

_.rk=function(a){for(var b=[],c=0,d=0;d<a.length;d++){for(var e=a.charCodeAt(d);255<e;)b[c++]=e&255,e>>=8;b[c++]=e}return b};
_.sk=function(a){for(var b=[],c=0,d=0;c<a.length;){var e=a[c++];if(128>e)b[d++]=String.fromCharCode(e);else if(191<e&&224>e){var f=a[c++];b[d++]=String.fromCharCode((e&31)<<6|f&63)}else if(239<e&&365>e){var f=a[c++],h=a[c++],k=a[c++],e=((e&7)<<18|(f&63)<<12|(h&63)<<6|k&63)-65536;b[d++]=String.fromCharCode(55296+(e>>10));b[d++]=String.fromCharCode(56320+(e&1023))}else f=a[c++],h=a[c++],b[d++]=String.fromCharCode((e&15)<<12|(f&63)<<6|h&63)}return b.join("")};
var tk,uk,vk,wk,yk,Bk,zk;tk=null;uk=null;vk=null;wk=_.Dd||_.Ed&&!_.qk||_.zd;_.xk=wk||"function"==typeof _.t.btoa;yk=wk||!_.qk&&!_.J&&"function"==typeof _.t.atob;_.Ak=function(a,b){zk();b=b?vk:tk;for(var c=[],d=0;d<a.length;d+=3){var e=a[d],f=d+1<a.length,h=f?a[d+1]:0,k=d+2<a.length,l=k?a[d+2]:0,m=e>>2,e=(e&3)<<4|h>>4,h=(h&15)<<2|l>>6,l=l&63;k||(l=64,f||(h=64));c.push(b[m],b[e],b[h],b[l])}return c.join("")};
_.Ck=function(a,b){if(yk&&!b)return _.t.atob(a);var c="";Bk(a,function(a){c+=String.fromCharCode(a)});return c};_.Dk=function(a){var b=[];Bk(a,function(a){b.push(a)});return b};Bk=function(a,b){function c(b){for(;d<a.length;){var c=a.charAt(d++),e=uk[c];if(null!=e)return e;if(!_.Mc(c))throw Error("G`"+c);}return b}zk();for(var d=0;;){var e=c(-1),f=c(0),h=c(64),k=c(64);if(64===k&&-1===e)break;b(e<<2|f>>4);64!=h&&(b(f<<4&240|h>>2),64!=k&&b(h<<6&192|k))}};
zk=function(){if(!tk){tk={};uk={};vk={};for(var a=0;65>a;a++)tk[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a),uk[tk[a]]=a,vk[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a),62<=a&&(uk["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a)]=a)}};

_.Fk=function(a){var b=_.Sj(a);if(String(a)!=b)throw Error("H");(a=b)&&"/"==a.charAt(a.length-1)||(a=(a||"")+"/");_.G.register("init",function(){_.Fk(a)});_.Ek=a;_.F.Wc(window.location.href)};_.Gk="function"==typeof window.atob;
var Hk,Ik,Jk,Kk,Lk,Mk,Nk;Hk=null;Ik=function(a,b){a={error:{code:-1,message:a}};if("/rpc"==b.url){b=b.body;for(var c=[],d=0;d<b.length;d++){var e=(0,_.Mb)(a),e=(0,_.Nb)(e);e.id=b[d].id;c.push(e)}a=c}return(0,_.Mb)(a)};
Jk=function(a,b,c,d){var e={};if(b)for(var f in b)if(Object.prototype.hasOwnProperty.call(b,f)){var h=_.ek(b,f),k=_.dk(f,h);k&&void 0!==h&&_.fk(e,k,h,!0)}b="number"===typeof c?c:void 0;d=d||void 0;f=_.ek(e,_.Lj.aC);c=_.ek(e,_.Lj.$B);if("base64"===f&&c){if(_.Gk)a=window.atob(a);else{if(!Hk)for(f="ABCDEFGHIJKLMNOPQRSTUVWXYZ",f+=f.toLowerCase()+"0123456789+/=",Hk={},h=0;h<f.length;h++)Hk[f.charAt(h)]=h;f=Hk;h=[];for(k=0;k<a.length;){var l=f[a.charAt(k++)],m=k<a.length?f[a.charAt(k)]:0;++k;var p=k<a.length?
f[a.charAt(k)]:0;++k;var q=k<a.length?f[a.charAt(k)]:0;++k;if(null==l||null==m||null==p||null==q)throw Error();h.push(l<<2|m>>4);64!=p&&(h.push(m<<4&240|p>>2),64!=q&&h.push(p<<6&192|q))}a=String.fromCharCode.apply(null,h)}f=/^(text\/[^\s;\/""]+|application\/(json(\+[^\s;\/""]*)?|([^\s;\/""]*\+)?xml))\s*(;|$)/i;_.fk(e,_.Lj.Ug,c,!0);if(c.match(/;\s*charset\s*=\s*("utf-?8"|utf-?8)\s*(;|$)/i)||c.match(f)&&!c.match(/;\s*charset\s*=/i))a=_.sk(_.rk(a));_.fk(e,_.Lj.aC);_.fk(e,_.Lj.$B)}return{body:a,headers:e,
status:b,statusText:d}};Kk=function(){try{return new window.XMLHttpRequest}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(a){}return null};Lk=function(a,b){b=b||"0.1";var c=[];c.push(a||"google-api-javascript-client");b&&(c.push("/"),c.push(b));return c.join("")};
Mk=function(a,b,c,d){a=a||{};var e=a.headers||{},f=a.httpMethod||"GET",h=String(a.url||""),k=a.urlParams||null,l=a.body||null,m=a.clientName||null,p=a.clientVersion||null;c=c||null;d=d||null;var h=_.Sj(h),h=_.Ek+String(h||"/").substr(1),h=_.zh(_.Bh([h],k)),q=[],k=[],w;for(w in e)if(Object.prototype.hasOwnProperty.call(e,w)){q.push(w);var x=_.ek(e,w);void 0!==x&&(w=_.ck(w,x))&&k.push([w,x])}for(;q.length;)delete e[q.pop()];for(;k.length;)q=k.pop(),_.fk(e,q[0],q[1]);_.fk(e,_.Lj.bC,Lk(m,p));_.fk(e,_.Lj.dL,
c||void 0);_.fk(e,_.Lj.cC,d||void 0);_.fk(e,_.Lj.ZK,"base64");l&&"object"===typeof l&&(l=(0,_.Mb)(l));var v=Kk();if(!v)throw Error("I");v.open(f,h);v.onreadystatechange=function(){if(4==v.readyState&&0!==v.status){var a=Jk(v.responseText,_.gk(v.getAllResponseHeaders(),!0),v.status,v.statusText);b(a)}};v.onerror=function(){var c=Ik("A network error occurred, and the request could not be completed.",a),c=Jk(c);b(c)};for(w in e)Object.prototype.hasOwnProperty.call(e,w)&&v.setRequestHeader((0,window.unescape)((0,window.encodeURIComponent)(w)),
(0,window.unescape)((0,window.encodeURIComponent)(e[w])));v.send(l?l:null)};Nk=function(a,b,c,d){var e={},f=0;if(0==a.length)b(e);else{var h=function(k){var l=k.key;k=k.params;try{Mk(k,function(c){e[l]={data:c};f++;a.length==f?b((0,_.Mb)(e)):h(a[f])},c,d)}catch(p){var m="";p&&(m+=" [",p.name&&(m+=p.name+": "),m+=p.message||String(p),m+="]");k=Ik("An error occurred, and the request could not be completed."+m,k);k=Jk(k);e[l]={data:k};f++;a.length==f?b((0,_.Mb)(e)):h(a[f])}};h(a[f])}};_.Bj=_.Bj||{};
_.Bj.V6=function(){_.G.register("makeHttpRequests",function(a){".."==this.f&&this.t==_.G.xn("..")&&this.origin==_.G.Hn("..")&&Nk.call(this,a,this.callback,this.origin,this.referer)})};_.Bj.xc=function(){var a=String(window.location.pathname);18<=a.length&&"/static/proxy.html"==a.substr(a.length-18)&&(a=a.substr(0,a.length-18));a||(a="/");_.Bj.fP(a)};_.Bj.fP=function(a){var b=_.Sj(a);if(String(a)!=b)throw Error("H");_.Bj.V6();_.Fk(a);_.G.call("..","ready:"+_.G.xn(".."))};
_.D("googleapis.ApiServer.makeHttpRequests",Nk);_.D("googleapis.ApiServer.initWithPath",_.Fk);_.D("googleapis.server.init",_.Bj.xc);_.D("googleapis.server.initWithPath",_.Bj.fP);
});
// Google Inc.
