/* JS */ gapi.loaded_0(function(_){var window=this;
var ba,ca,da,ha,ia,Fa,Ga;
for(_.g,_.n=function(a){return function(){return ba[a].apply(this,arguments)}},_.r=function(a,b){return ba[a]=b},_._DumpException=function(a){throw a;},ba=[],ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},da="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this,
ha=["String","prototype","startsWith"],ia=0;ia<ha.length-1;ia++){var ka=ha[ia];ka in da||(da[ka]={});da=da[ka]}
var la=ha[ha.length-1],pa=da[la],qa=pa?pa:function(a,b){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");c=this+"";a+="";var d=c.length,e=a.length;b=Math.max(0,Math.min(b|0,c.length));for(var f=0;f<e&&b<d;)if(c[b++]!=a[f++])return!1;return f>=e};qa!=pa&&null!=qa&&ca(da,la,{configurable:!0,writable:!0,value:qa});
_.xa=_.xa||{};_.t=this;_.za=function(a){return void 0!==a};
_.Aa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.Ba=function(a){return"array"==_.Aa(a)};_.Ca=function(a){var b=_.Aa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.u=function(a){return"string"==typeof a};_.Da="closure_uid_"+(1E9*Math.random()>>>0);Fa=function(a,b,c){return a.call.apply(a.bind,arguments)};
Ga=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.z=function(a,b,c){_.z=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?Fa:Ga;return _.z.apply(null,arguments)};_.Ia=Date.now||function(){return+new Date};
_.A=function(a,b){function c(){}c.prototype=b.prototype;a.R=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Is=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.La=window.osapi=window.osapi||{};_.google=window.google||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{rms:"migrated"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},udc_webconsentflow:{url:"https://myaccount.google.com/webconsent?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},
requestCache:{enabled:!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:!0},transport:{isProxyShared:!0},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});

/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
_.D=function(a,b){a=a.split(".");var c=_.t;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.za(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}};_.Oa=window;_.Pa=window.document;_.Qa=_.Oa.location;_.Ra=/\[native code\]/;_.Sa=function(a,b,c){return a[b]=a[b]||c};_.Ta=function(){var a;if((a=Object.create)&&_.Ra.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.Ua=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)}; _.Va=function(a,b){a=a||{};for(var c in a)_.Ua(a,c)&&(b[c]=a[c])};_.Wa=_.Sa(_.Oa,"gapi",{});
_.Xa=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.Ya=new RegExp(/^/.source+/([a-zA-Z][-+.a-zA-Z0-9]*:)?/.source+/(\/\/[^\/?#]*)?/.source+/([^?#]*)?/.source+/(\?([^#]*))?/.source+/(#((#|[^#])*))?/.source+/$/.source);
_.Za=new RegExp(/(%([^0-9a-fA-F%]|[0-9a-fA-F]([^0-9a-fA-F%])?)?)*/.source+/%($|[^0-9a-fA-F]|[0-9a-fA-F]($|[^0-9a-fA-F]))/.source,"g");_.ab=function(){return _.Oa.location.origin||_.Oa.location.protocol+"//"+_.Oa.location.host};_.bb=new RegExp(/\/?\??#?/.source+"("+/[\/?#]/i.source+"|"+/[\uD800-\uDBFF]/i.source+"|"+/%[c-f][0-9a-f](%[89ab][0-9a-f]){0,2}(%[89ab]?)?/i.source+"|"+/%[0-9a-f]?/i.source+")$","i");
_.fb=function(a,b,c){_.eb(a,b,c,"add","at")};_.eb=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.gb=_.Sa(_.Oa,"___jsl",_.Ta());_.Sa(_.gb,"I",0);_.Sa(_.gb,"hel",10);var hb,kb,lb,nb,pb,qb;hb=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};kb=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};lb=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};nb=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]&&b[c]&&"object"===typeof a[c]&&"object"===typeof b[c]&&!lb(a[c])&&!lb(b[c])?nb(a[c],b[c]):b[c]&&"object"===typeof b[c]?(a[c]=lb(b[c])?[]:{},nb(a[c],b[c])):a[c]=b[c])};
pb=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var b;try{b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
qb=function(a){kb(!0);var b=window.___gcfg,c=hb("cu");if(b&&b!==window.___gu){var d={};nb(d,b);c.push(d);window.___gu=b}var b=hb("cu"),e=window.document.scripts||window.document.getElementsByTagName("script")||[],d=[],f=[];f.push.apply(f,hb("us"));for(var h=0;h<e.length;++h)for(var k=e[h],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",
!0),(f=d[e])?(h=f.nodeType,f=3==h||4==h?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=pb(f))&&b.push(f));a&&(d={},nb(d,a),c.push(d));d=hb("cd");a=0;for(b=d.length;a<b;++a)nb(kb(),d[a]);d=hb("ci");a=0;for(b=d.length;a<b;++a)nb(kb(),d[a]);a=0;for(b=c.length;a<b;++a)nb(kb(),c[a])};_.E=function(a,b){if(!a)return kb();a=a.split("/");for(var c=kb(),d=0,e=a.length;c&&"object"===typeof c&&d<e;++d)c=c[a[d]];return d===a.length&&void 0!==c?c:b}; _.rb=function(a,b){var c=a;if("string"===typeof a){var d=c={};a=a.split("/");for(var e=0,f=a.length;e<f-1;++e)var h={},d=d[a[e]]=h;d[a[e]]=b}qb(c)};
var tb=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.Sa(_.gb,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};tb&&tb();qb();_.D("gapi.config.get",_.E);_.D("gapi.config.update",_.rb);
(function(){function a(a,b){if(!(a<c)&&d)if(2===a&&d.warn)d.warn(b);else if(3===a&&d.error)try{d.error(b)}catch(h){}else d.log&&d.log(b)}var b=function(b){a(1,b)};_.Ja=function(b){a(2,b)};_.Ka=function(b){a(3,b)};_.wb=function(){};b.INFO=1;b.WARNING=2;b.NONE=4;var c=1,d=window.console?window.console:window.opera?window.opera.postError:void 0;return b})();

_.F=_.F||{};
_.F=_.F||{};(function(){var a=[];_.F.Wja=function(b){a.push(b)};_.F.jka=function(){for(var b=0,c=a.length;b<c;++b)a[b]()}})();
_.xb=function(a){return!!a&&"object"===typeof a&&_.Ra.test(a.push)};_.yb=function(a,b){var c=_.Sa(_.gb,"watt",_.Ta());_.Sa(c,a,b)};_.F=_.F||{};
(function(){var a=null;_.F.Wc=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");for(var e=window.decodeURIComponent?window.decodeURIComponent:window.unescape,f=0,h=b.length;f<h;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k),k=b[f].substring(k+1),k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(m){}}}c&&(a=d);return d}; _.F.Wc()})();
_.D("gadgets.util.getUrlParameters",_.F.Wc);
_.Ab=window.console;_.Bb=function(a){_.Ab&&_.Ab.log&&_.Ab.log(a)};_.Cb=function(){};
_.Db=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&_.rb(a());return{register:function(a,c,d){d&&d(_.E())},get:function(a){return _.E(a)},update:function(a,c){if(c)throw"Config replacement is not supported";_.rb(a)},xc:function(){}}}();
_.D("gadgets.config.register",_.Db.register);_.D("gadgets.config.get",_.Db.get);_.D("gadgets.config.init",_.Db.xc);_.D("gadgets.config.update",_.Db.update);
var Eb=function(a){return 10>a?"0"+a:a},Fb={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},Hb=function(a){var b,c,d;b=/[\"\\\x00-\x1f\x7f-\x9f]/g;if(void 0!==a){switch(typeof a){case "string":return b.test(a)?'"'+a.replace(b,function(a){var b=Fb[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";
b=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){d=a.length;for(c=0;c<d;c+=1)b.push(Hb(a[c])||"null");return"["+b.join(",")+"]"}for(c in a)!/___$/.test(c)&&_.Ua(a,c)&&"string"===typeof c&&(d=Hb(a[c]))&&b.push(Hb(c)+":"+d);return"{"+b.join(",")+"}"}return""}},Ib=function(a){if(!a)return!1;if(/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))try{return eval("("+
a+")")}catch(b){}return!1},Jb=!1,Kb;try{Jb=!!window.JSON&&'["a"]'===window.JSON.stringify(["a"])&&"a"===window.JSON.parse('["a"]')[0]}catch(a){}Kb=function(a){try{return window.JSON.parse(a)}catch(b){return!1}};_.Mb=Jb?window.JSON.stringify:Hb;_.Nb=Jb?Kb:Ib;Kb||(Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",Eb(this.getUTCMonth()+1),"-",Eb(this.getUTCDate()),"T",Eb(this.getUTCHours()),":",Eb(this.getUTCMinutes()),":",Eb(this.getUTCSeconds()),"Z"].join("")});

_.D("gadgets.json.stringify",_.Mb);_.D("gadgets.json.parse",_.Nb);_.Xa(_.Oa.location.href,"rpctoken")&&_.fb(_.Pa,"unload",function(){});
var Qb;_.Ob=function(){var a=_.Pa.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.Pb=function(a){if(_.Ob())a();else{var b=!1,c=function(){if(!b)return b=!0,a.apply(this,arguments)};_.Oa.addEventListener?(_.Oa.addEventListener("load",c,!1),_.Oa.addEventListener("DOMContentLoaded",c,!1)):_.Oa.attachEvent&&(_.Oa.attachEvent("onreadystatechange",function(){_.Ob()&&c.apply(this,arguments)}),_.Oa.attachEvent("onload",c))}};Qb=Qb||{};Qb.VR=null; Qb.oQ=null;Qb.Vy=null;Qb.frameElement=null;
Qb=Qb||{};
Qb.CJ||(Qb.CJ=function(){function a(a){"undefined"!=typeof window.addEventListener?window.addEventListener("message",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onmessage",a);window.___jsl=window.___jsl||{};var b=window.___jsl;b.RPMQ=b.RPMQ||[];b.RPMQ.push(a)}function b(a){var b=(0,_.Nb)(a.data);if(b&&b.f){(0,_.wb)("gadgets.rpc.receive("+window.name+"): "+a.data);var d=_.G.Hn(b.f);e&&("undefined"!==typeof a.origin?a.origin!==d:a.domain!==/^.+:\/\/([^:]+).*/.exec(d)[1])?_.Ka("Invalid rpc message origin. "+
d+" vs "+(a.origin||"")):c(b,a.origin)}}var c,d,e=!0;return{Jp:function(){return"wpm"},l4:function(){return!0},xc:function(f,h){_.Db.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(e=!1)});c=f;d=h;a(b);d("..",!0);return!0},xd:function(a){d(a,!0);return!0},call:function(a,b,c){var d=_.G.Hn(a),e=_.G.fL(a);d?window.setTimeout(function(){var a=(0,_.Mb)(c);(0,_.wb)("gadgets.rpc.send("+window.name+"): "+a);e.postMessage(a,d)},0):".."!=a&&_.Ka("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.G&&_.G||(_.G=window.gadgets.rpc,_.G.config=_.G.config,_.G.register=_.G.register,_.G.unregister=_.G.unregister,_.G.yR=_.G.registerDefault,_.G.TT=_.G.unregisterDefault,_.G.kN=_.G.forceParentVerifiable,_.G.call=_.G.call,_.G.$t=_.G.getRelayUrl,_.G.uj=_.G.setRelayUrl,_.G.EA=_.G.setAuthToken,_.G.Qv=_.G.setupReceiver,_.G.xn=_.G.getAuthToken,_.G.tH=_.G.removeReceiver,_.G.SN=_.G.getRelayChannel,_.G.uR=_.G.receive,_.G.vR=_.G.receiveSameDomain,_.G.mb=
_.G.getOrigin,_.G.Hn=_.G.getTargetOrigin,_.G.fL=_.G._getTargetWin,_.G.UX=_.G._parseSiblingId);else{_.G=function(){function a(a,b){if(!ja[a]){var c=M;b||(c=ua);ja[a]=c;b=sa[a]||[];for(var d=0;d<b.length;++d){var e=b[d];e.t=N[a];c.call(a,e.f,e)}sa[a]=[]}}function b(){function a(){sb=!0}V||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),V=!0)}function c(a,c,d,e,f){N[c]&&N[c]===d||(_.Ka("Invalid gadgets.rpc token. "+
N[c]+" vs "+d),na(c,2));f.onunload=function(){L[c]&&!sb&&(na(c,1),_.G.tH(c))};b();e=(0,_.Nb)((0,window.decodeURIComponent)(e))}function d(b,c){if(b&&"string"===typeof b.s&&"string"===typeof b.f&&b.a instanceof Array)if(N[b.f]&&N[b.f]!==b.t&&(_.Ka("Invalid gadgets.rpc token. "+N[b.f]+" vs "+b.t),na(b.f,2)),"__ack"===b.s)window.setTimeout(function(){a(b.f,!0)},0);else{b.c&&(b.callback=function(a){_.G.call(b.f,(b.g?"legacy__":"")+"__cb",null,b.c,a)});if(c){var d=e(c);b.origin=c;var f=b.r,h;try{h=e(f)}catch(oa){}f&&
h==d||(f=c);b.referer=f}c=(y[b.s]||y[""]).apply(b,b.a);b.c&&"undefined"!==typeof c&&_.G.call(b.f,"__cb",null,b.c,c)}}function e(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a)throw Error("b");
var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c}function f(a){if("/"==a.charAt(0)){var b=a.indexOf("|");return{id:0<b?a.substring(1,b):a.substring(1),origin:0<b?a.substring(b+1):null}}return null}function h(a){if("undefined"===typeof a||".."===a)return window.parent;var b=f(a);if(b)return window.top.frames[b.id];a=String(a);return(b=window.frames[a])?b:(b=window.document.getElementById(a))&&b.contentWindow?
b.contentWindow:null}function k(a,b){if(!0!==L[a]){"undefined"===typeof L[a]&&(L[a]=0);var c=h(a);".."!==a&&null==c||!0!==M.xd(a,b)?!0!==L[a]&&10>L[a]++?window.setTimeout(function(){k(a,b)},500):(ja[a]=ua,L[a]=!0):L[a]=!0}}function l(a){(a=B[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function m(a,b,c){b&&!/http(s)?:\/\/.+/.test(b)&&(0==b.indexOf("//")?b=window.location.protocol+
b:"/"==b.charAt(0)?b=window.location.protocol+"//"+window.location.host+b:-1==b.indexOf("://")&&(b=window.location.protocol+"//"+b));B[a]=b;"undefined"!==typeof c&&(H[a]=!!c)}function p(a,b){b=b||"";N[a]=String(b);k(a,b)}function q(a){a=(a.passReferrer||"").split(":",2);Na=a[0]||"none";aa=a[1]||"origin"}function w(b){"true"===String(b.useLegacyProtocol)&&(M=Qb.Vy||ua,M.xc(d,a))}function x(a,b){function c(c){c=c&&c.rpc||{};q(c);var d=c.parentRelayUrl||"",d=e(Y.parent||b)+d;m("..",d,"true"===String(c.useLegacyProtocol));
w(c);p("..",a)}!Y.parent&&b?c({}):_.Db.register("rpc",null,c)}function v(a,b,c){if(".."===a)x(c||Y.rpctoken||Y.ifpctok||"",b);else a:{var d=null;if("/"!=a.charAt(0)){if(!_.F)break a;d=window.document.getElementById(a);if(!d)throw Error("c`"+a);}d=d&&d.src;b=b||_.G.mb(d);m(a,b);b=_.F.Wc(d);p(a,c||b.rpctoken)}}var y={},B={},H={},N={},C=0,K={},L={},Y={},ja={},sa={},Na=null,aa=null,fa=window.top!==window.self,va=window.name,na=function(){},ob=window.console,wa=ob&&ob.log&&function(a){ob.log(a)}||function(){},
ua=function(){function a(a){return function(){wa(a+": call ignored")}}return{Jp:function(){return"noop"},l4:function(){return!0},xc:a("init"),xd:a("setup"),call:a("call")}}();_.F&&(Y=_.F.Wc());var sb=!1,V=!1,M=function(){if("rmr"==Y.rpctx)return Qb.VR;var a="function"===typeof window.postMessage?Qb.CJ:"object"===typeof window.postMessage?Qb.CJ:window.ActiveXObject?Qb.oQ?Qb.oQ:Qb.Vy:0<window.navigator.userAgent.indexOf("WebKit")?Qb.VR:"Gecko"===window.navigator.product?Qb.frameElement:Qb.Vy;a||(a=
ua);return a}();y[""]=function(){wa("Unknown RPC service: "+this.s)};y.__cb=function(a,b){var c=K[a];c&&(delete K[a],c.call(this,b))};return{config:function(a){"function"===typeof a.cS&&(na=a.cS)},register:function(a,b){if("__cb"===a||"__ack"===a)throw Error("d");if(""===a)throw Error("e");y[a]=b},unregister:function(a){if("__cb"===a||"__ack"===a)throw Error("f");if(""===a)throw Error("g");delete y[a]},yR:function(a){y[""]=a},TT:function(){delete y[""]},kN:function(){},call:function(a,b,c,d){a=a||
"..";var e="..";".."===a?e=va:"/"==a.charAt(0)&&(e=_.G.mb(window.location.href),e="/"+va+(e?"|"+e:""));++C;c&&(K[C]=c);var h={s:b,f:e,c:c?C:0,a:Array.prototype.slice.call(arguments,3),t:N[a],l:!!H[a]},k;a:if("bidir"===Na||"c2p"===Na&&".."===a||"p2c"===Na&&".."!==a){k=window.location.href;var l="?";if("query"===aa)l="#";else if("hash"===aa)break a;l=k.lastIndexOf(l);l=-1===l?k.length:l;k=k.substring(0,l)}else k=null;k&&(h.r=k);if(".."===a||null!=f(a)||window.document.getElementById(a))(k=ja[a])||null===
f(a)||(k=M),0===b.indexOf("legacy__")&&(k=M,h.s=b.substring(8),h.c=h.c?h.c:C),h.g=!0,h.r=e,k?(H[a]&&(k=Qb.Vy),!1===k.call(a,e,h)&&(ja[a]=ua,M.call(a,e,h))):sa[a]?sa[a].push(h):sa[a]=[h]},$t:l,uj:m,EA:p,Qv:v,xn:function(a){return N[a]},tH:function(a){delete B[a];delete H[a];delete N[a];delete L[a];delete ja[a]},SN:function(){return M.Jp()},uR:function(a,b){4<a.length?M.hia(a,d):c.apply(null,a.concat(b))},vR:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){d(a)},0)},mb:e,
Hn:function(a){var b=null,c=l(a);c?b=c:(c=f(a))?b=c.origin:".."==a?b=Y.parent:(a=window.document.getElementById(a))&&"iframe"===a.tagName.toLowerCase()&&(b=a.src);return e(b)},xc:function(){!1===M.xc(d,a)&&(M=ua);fa?v(".."):_.Db.register("rpc",null,function(a){a=a.rpc||{};q(a);w(a)})},fL:h,UX:f,n$:"__ack",Nfa:va||"..",cga:0,bga:1,aga:2}}();_.G.xc()};
_.G.config({cS:function(a){throw Error("h`"+a);}});_.wb=_.Cb;_.D("gadgets.rpc.config",_.G.config);_.D("gadgets.rpc.register",_.G.register);_.D("gadgets.rpc.unregister",_.G.unregister);_.D("gadgets.rpc.registerDefault",_.G.yR);_.D("gadgets.rpc.unregisterDefault",_.G.TT);_.D("gadgets.rpc.forceParentVerifiable",_.G.kN);_.D("gadgets.rpc.call",_.G.call);_.D("gadgets.rpc.getRelayUrl",_.G.$t);_.D("gadgets.rpc.setRelayUrl",_.G.uj);_.D("gadgets.rpc.setAuthToken",_.G.EA);_.D("gadgets.rpc.setupReceiver",_.G.Qv);_.D("gadgets.rpc.getAuthToken",_.G.xn); _.D("gadgets.rpc.removeReceiver",_.G.tH);_.D("gadgets.rpc.getRelayChannel",_.G.SN);_.D("gadgets.rpc.receive",_.G.uR);_.D("gadgets.rpc.receiveSameDomain",_.G.vR);_.D("gadgets.rpc.getOrigin",_.G.mb);_.D("gadgets.rpc.getTargetOrigin",_.G.Hn);

_.F=_.F||{};_.F.bx=function(a,b,c,d){"undefined"!=typeof a.addEventListener?a.addEventListener(b,c,d):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+b,c):_.Ja("cannot attachBrowserEvent: "+b)};_.F.X6=function(a){var b=window;b.removeEventListener?b.removeEventListener("mousemove",a,!1):b.detachEvent?b.detachEvent("onmousemove",a):_.Ja("cannot removeBrowserEvent: mousemove")};

_.Cj=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;p=m=0}function b(a){for(var b=h,c=0;64>c;c+=4)b[c/4]=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];for(c=16;80>c;c++)a=b[c-3]^b[c-8]^b[c-14]^b[c-16],b[c]=(a<<1|a>>>31)&4294967295;a=e[0];for(var d=e[1],f=e[2],k=e[3],l=e[4],m,p,c=0;80>c;c++)40>c?20>c?(m=k^d&(f^k),p=1518500249):(m=d^f^k,p=1859775393):60>c?(m=d&f|k&(d|f),p=2400959708):(m=d^f^k,p=3395469782),m=((a<<5|a>>>27)&4294967295)+m+l+p+b[c]&4294967295,
l=k,k=f,f=(d<<30|d>>>2)&4294967295,d=a,a=m;e[0]=e[0]+a&4294967295;e[1]=e[1]+d&4294967295;e[2]=e[2]+f&4294967295;e[3]=e[3]+k&4294967295;e[4]=e[4]+l&4294967295}function c(a,c){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var d=[],e=0,h=a.length;e<h;++e)d.push(a.charCodeAt(e));a=d}c||(c=a.length);d=0;if(0==m)for(;d+64<c;)b(a.slice(d,d+64)),d+=64,p+=64;for(;d<c;)if(f[m++]=a[d++],p++,64==m)for(m=0,b(f);d+64<c;)b(a.slice(d,d+64)),d+=64,p+=64}function d(){var a=[],
d=8*p;56>m?c(k,56-m):c(k,64-(m-56));for(var h=63;56<=h;h--)f[h]=d&255,d>>>=8;b(f);for(h=d=0;5>h;h++)for(var l=24;0<=l;l-=8)a[d++]=e[h]>>l&255;return a}for(var e=[],f=[],h=[],k=[128],l=1;64>l;++l)k[l]=0;var m,p;a();return{reset:a,update:c,digest:d,Th:function(){for(var a=d(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b}}};
_.Dj=function(){function a(a){var b=_.Cj();b.update(a);return b.Th()}var b=window.crypto;if(b&&"function"==typeof b.getRandomValues)return function(){var a=new window.Uint32Array(1);b.getRandomValues(a);return Number("0."+a[0])};var c=_.E("random/maxObserveMousemove");null==c&&(c=-1);var d=0,e=Math.random(),f=1,h=1E6*(window.screen.width*window.screen.width+window.screen.height),k=function(a){a=a||window.event;var b=a.screenX+a.clientX<<16,b=b+(a.screenY+a.clientY),b=(new Date).getTime()%1E6*b;f=
f*b%h;0<c&&++d==c&&_.F.X6(k)};0!=c&&_.F.bx(window,"mousemove",k,!1);var l=a(window.document.cookie+"|"+window.document.location+"|"+(new Date).getTime()+"|"+e);return function(){var b=f,b=b+(0,window.parseInt)(l.substr(0,20),16);l=a(l);return b/(h+Math.pow(16,20))}}();
_.D("shindig.random",_.Dj);
});
// Google Inc.
